---
title: "First Knit"
author: "Annabelle Polack"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer     
  
I attended high school at Littlerock High, yes I did graduate with a B average. The graduation ceremony wasn't that great though. English class is a little easier for me to understand in some ways. Math in certain areas I do understand and am great at. The subject I was best in was my art, painting, theater, and drawing classes. 
     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
  
The computer I have at home is a Windows laptop. I would rate myself at a 8.9 when it comes to my computer and a lot of computer programs, as long as I get some time to mess around with the computer or program. I do have internet acess, it's usually really good until a lot of people start using the wifi with too many devices.    

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
  
 The name I prefer to be called is Annabelle which is my fisrt name. I have a lot of nicknames due to family so I usually only let my family use them.  
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
  
I want to become a well known photographer, or to just start my own photography studio to take pictures of animals, or maternity portraits. The subjects that would be the most help to me are the photography classes, so I can better get to know how to use my camera and equipment. The degree I am trying to get is my AA in photography or I would also like to get my certificate for photography.   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
  
No I have never traveled outside the United States. I would love to travel to Japan, Germany, Ireland, Scotland, and Iceland.No I have never been in the military. I would not want to be drafted, due to the fact that the wars are being fought due to oil and is basically for the rich and not actually for the country.    
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer     
  
I took math 115 in my previous semester, because math wise I understand sats the best. I did not know about 116 being accepted for different institutes. The grade I would need would be a B at best or at least a C.    
 






  




